# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all

pierre = User.create!(email: 'pierre.liduena@gmail.com', password: '123456', first_name: 'pierre', last_name: 'liduena', adress: '58 rue de buzenval', postal_code: '33000', city:'paris', phone:'0000000000', birth_day: '24/11/1988' )


Event.destroy_all

Event.create!(etape: 'Etape 1', name: ' La Jaques Gouin', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae sit, natus expedita consectetur quas, est sint asperiores in dicta eos sapiente consequatur voluptatem libero, tempore provident, voluptatum unde id modi. ', place:'Breuillet (91)', date:'1er mai', statut:'à venir', longitude: '45.1', latitude:'3.4833', picture:'event_jacques_gouin.jpg')
Event.create!(etape: 'Etape 1', name: ' La Jaques Gouin', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae sit, natus expedita consectetur quas, est sint asperiores in dicta eos sapiente consequatur voluptatem libero, tempore provident, voluptatum unde id modi. ', place:'Breuillet (91)', date:'1er mai', statut:'à venir', longitude: '45.1', latitude:'3.4833', picture:'event_jacques_gouin.jpg')
Event.create!(etape: 'Etape 1', name: ' La Jaques Gouin', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae sit, natus expedita consectetur quas, est sint asperiores in dicta eos sapiente consequatur voluptatem libero, tempore provident, voluptatum unde id modi. ', place:'Breuillet (91)', date:'1er mai', statut:'à venir', longitude: '45.1', latitude:'3.4833', picture:'event_jacques_gouin.jpg')
Event.create!(etape: 'Etape 1', name: ' La Jaques Gouin', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae sit, natus expedita consectetur quas, est sint asperiores in dicta eos sapiente consequatur voluptatem libero, tempore provident, voluptatum unde id modi. ', place:'Breuillet (91)', date:'1er mai', statut:'à venir', longitude: '45.1', latitude:'3.4833', picture:'event_jacques_gouin.jpg')
Event.create!(etape: 'Etape 1', name: ' La Jaques Gouin', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae sit, natus expedita consectetur quas, est sint asperiores in dicta eos sapiente consequatur voluptatem libero, tempore provident, voluptatum unde id modi. ', place:'Breuillet (91)', date:'1er mai', statut:'à venir', longitude: '45.1', latitude:'3.4833', picture:'event_jacques_gouin.jpg')
Event.create!(etape: 'Etape 1', name: ' La Jaques Gouin', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae sit, natus expedita consectetur quas, est sint asperiores in dicta eos sapiente consequatur voluptatem libero, tempore provident, voluptatum unde id modi. ', place:'Breuillet (91)', date:'1er mai', statut:'à venir', longitude: '45.1', latitude:'3.4833', picture:'event_jacques_gouin.jpg')
Event.create!(etape: 'Etape 1', name: ' La Jaques Gouin', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae sit, natus expedita consectetur quas, est sint asperiores in dicta eos sapiente consequatur voluptatem libero, tempore provident, voluptatum unde id modi. ', place:'Breuillet (91)', date:'1er mai', statut:'à venir', longitude: '45.1', latitude:'3.4833', picture:'event_jacques_gouin.jpg')
Event.create!(etape: 'Etape 1', name: ' La Jaques Gouin', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae sit, natus expedita consectetur quas, est sint asperiores in dicta eos sapiente consequatur voluptatem libero, tempore provident, voluptatum unde id modi. ', place:'Breuillet (91)', date:'1er mai', statut:'à venir', longitude: '45.1', latitude:'3.4833', picture:'event_jacques_gouin.jpg')
Event.create!(etape: 'Etape 1', name: ' La Jaques Gouin', description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae sit, natus expedita consectetur quas, est sint asperiores in dicta eos sapiente consequatur voluptatem libero, tempore provident, voluptatum unde id modi. ', place:'Breuillet (91)', date:'1er mai', statut:'à venir', longitude: '45.1', latitude:'3.4833', picture:'event_jacques_gouin.jpg')


Product.destroy_all

Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_maillot_homme.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_maillot_femme.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_maillot_jaune.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_pedaleur.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_abbie_et_rose.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_2_abbie_et_rose.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_baristea.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_bv.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_cafedelatour.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_dooble.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_easyin.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_embrocation.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_gasp.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_greves.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_helpmybike.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_JBL.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_junglespeed.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_kronos.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_occabike.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_pokemon.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_taraking.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_timesup.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_urban_challenge_code_promo.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_urban_cours.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_velco1.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_velco2.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_velodrome.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_lagazelle1.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_lagazelle2.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_demonte_pneu.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_sac_lcl.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_roue_asterion.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_chaussures_cycleslaurent.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_chaussettes_assurancesvelo.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_casque_cycleslaurent.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_code_promo_50.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_code_promo.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_baristea_the.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_baristea_cafe.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_gants.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_garde_boue.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_garmin_cycleslaurent.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')
Product.create!(name: 'Pedaleur', description: '3 box à gagner', picture:'lot_porteclef_goodicom.jpg', score:'1er de chaque cathé', text:'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit tenetur harum sed, quos possimus voluptates. Ipsum nobis, porro magni praesentium obcaecati quod facere beatae assumenda doloremque culpa, unde voluptatum error.', url: 'https://www.pedaleur.fr/')







Race.destroy_all

Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')
Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')
Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')
Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')
Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')
Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')
Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')
Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')
Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')
Race.create!(name: 'Claudio', distance: 100, price: 30, description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore delectus officia voluptate ducimus, qui ut tempora officiis? Ea tenetur, suscipit aliquam odit, eligendi earum nam, distinctio deserunt maxime quod aut!', elevation:'1000', date:'1er mai', place:'Breuillet', picture:'event_jacques_gouin.jpg')



AdminUser.create!(email: 'assurancesvelo@gmail.com', password: 'challenge', password_confirmation: 'challenge')
